#!/usr/bin/env python3
"""有料コンテンツ（tier=paid の偉人・悩み＋全聖典＋全伝説）を D1 投入用 seed.sql に書き出す。
無料(tier=free)はクライアント同梱のままなので含めない。
使い方:  python3 server/build-seed.py   →  server/seed.sql
投入:    wrangler d1 execute eichi-db --file server/schema.sql
         wrangler d1 execute eichi-db --file server/seed.sql
"""
import json, os, time

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)
sages = json.load(open(os.path.join(root, "data", "sages.json"), encoding="utf-8"))
events = json.load(open(os.path.join(root, "data", "events.json"), encoding="utf-8"))
legends = json.load(open(os.path.join(root, "data", "legends.json"), encoding="utf-8"))

def esc(s):  # SQL文字列リテラル用（シングルクォートを2重化）
    return s.replace("'", "''")

rows = []
now = int(time.time())
def add(t, _id, tier, obj):
    rows.append("INSERT OR REPLACE INTO content (type,id,tier,payload,updated_at) VALUES ('%s','%s','%s','%s',%d);"
                % (t, esc(_id), esc(tier or "paid"), esc(json.dumps(obj, ensure_ascii=False)), now))

paid_sages = 0
for s in sages["sages"]:
    if s["id"] == "original":      # 無料ナレーターはクライアント側
        continue
    if s.get("tier") == "free":    # 入門3人はクライアント側
        continue
    add("sage", s["id"], "paid", s); paid_sages += 1

paid_events = 0
for e in events["events"]:
    if e.get("tier") == "free":
        continue
    add("event", e["id"], "paid", e); paid_events += 1

for l in legends["legends"]:
    add("legend", l["id"], "paid", l)

out = os.path.join(here, "seed.sql")
with open(out, "w", encoding="utf-8") as f:
    f.write("-- AUTO-GENERATED by server/build-seed.py — 有料コンテンツのみ\n")
    f.write("DELETE FROM content;\n")
    f.write("\n".join(rows) + "\n")
print("wrote server/seed.sql  (paid sages: %d, paid events: %d, legends: %d)"
      % (paid_sages, paid_events, len(legends["legends"])))
