#!/usr/bin/env python3
"""data/*.json（正典）から、ブラウザが file:// で直接読める data/gamedata.js を生成する。
sages.json / events.json を編集したら、このスクリプトを再実行すること。"""
import json, os

here = os.path.dirname(os.path.abspath(__file__))
sages = json.load(open(os.path.join(here, "data", "sages.json"), encoding="utf-8"))
events = json.load(open(os.path.join(here, "data", "events.json"), encoding="utf-8"))
legends = json.load(open(os.path.join(here, "data", "legends.json"), encoding="utf-8"))

bundle = {"sages": sages, "events": events, "legends": legends}
out = (
    "// AUTO-GENERATED by build-data.py from data/sages.json + data/events.json + data/legends.json.\n"
    "// 手で編集しないこと。データは JSON を編集 → `python3 build-data.py` で再生成。\n"
    "window.GAME_DATA = " + json.dumps(bundle, ensure_ascii=False, indent=2) + ";\n"
)
open(os.path.join(here, "data", "gamedata.js"), "w", encoding="utf-8").write(out)
print("wrote data/gamedata.js  (sages: %d, events: %d, legends: %d)" % (
    len(sages["sages"]), len(events["events"]), len(legends["legends"])))

# --- 無料のみのバンドル（サーバー化の本番切替で使う / 有料はAPI取得） ---
free_sages = {
    "version": sages.get("version", 1),
    "ranks": sages["ranks"],
    "sages": [s for s in sages["sages"] if s["id"] == "original" or s.get("tier") == "free"],
}
free_events = {"version": events.get("version", 1), "categories": events.get("categories", []),
               "events": [e for e in events["events"] if e.get("tier") == "free"]}
free_bundle = {"sages": free_sages, "events": free_events, "legends": {"version": 1, "legends": []}}
free_out = (
    "// AUTO-GENERATED by build-data.py — 無料のみ（有料はAPIから取得）。本番サーバー化時に index.html でこちらを読む。\n"
    "window.GAME_DATA = " + json.dumps(free_bundle, ensure_ascii=False, indent=2) + ";\n"
)
open(os.path.join(here, "data", "gamedata.free.js"), "w", encoding="utf-8").write(free_out)
print("wrote data/gamedata.free.js  (free sages: %d, free events: %d)" % (
    len(free_sages["sages"]), len(free_events["events"])))
