#!/usr/bin/env python3
"""data/*.json（正典）から、ブラウザが file:// で直接読める data/gamedata.js を生成する。
sages.json / events.json を編集したら、このスクリプトを再実行すること。"""
import json, os

here = os.path.dirname(os.path.abspath(__file__))
sages = json.load(open(os.path.join(here, "data", "sages.json"), encoding="utf-8"))
events = json.load(open(os.path.join(here, "data", "events.json"), encoding="utf-8"))
legends = json.load(open(os.path.join(here, "data", "legends.json"), encoding="utf-8"))

bundle = {"sages": sages, "events": events, "legends": legends}
out = (
    "// AUTO-GENERATED by build-data.py from data/sages.json + data/events.json + data/legends.json.\n"
    "// 手で編集しないこと。データは JSON を編集 → `python3 build-data.py` で再生成。\n"
    "window.GAME_DATA = " + json.dumps(bundle, ensure_ascii=False, indent=2) + ";\n"
)
open(os.path.join(here, "data", "gamedata.js"), "w", encoding="utf-8").write(out)
print("wrote data/gamedata.js  (sages: %d, events: %d, legends: %d)" % (
    len(sages["sages"]), len(events["events"]), len(legends["legends"])))
