// AUTO-GENERATED by build-data.py — 無料のみ（有料はAPIから取得）。本番サーバー化時に index.html でこちらを読む。
window.GAME_DATA = {
  "sages": {
    "version": 1,
    "ranks": {
      "1": {
        "title": "灯をともす者",
        "unlockWisdom": 0
      },
      "2": {
        "title": "学びの芽",
        "unlockWisdom": 10
      },
      "3": {
        "title": "問いを持つ者",
        "unlockWisdom": 25
      },
      "4": {
        "title": "思索の人",
        "unlockWisdom": 45
      },
      "5": {
        "title": "賢慮の士",
        "unlockWisdom": 70
      },
      "6": {
        "title": "大賢者",
        "unlockWisdom": 100
      },
      "7": {
        "title": "達観の人",
        "unlockWisdom": 135
      },
      "8": {
        "title": "伝説の探究者",
        "unlockWisdom": 175
      },
      "9": {
        "title": "神聖なる導き",
        "unlockWisdom": 230
      },
      "10": {
        "title": "叡智皆伝",
        "unlockWisdom": 290
      }
    },
    "sages": [
      {
        "id": "original",
        "name": "灯火の声",
        "nameEn": "The Inner Light",
        "region": "-",
        "field": "narrator",
        "stance": "warm",
        "rank": 0,
        "isPremium": false,
        "packId": null,
        "color": "#caa45d",
        "desc": "無料で寄り添うナレーター。実在人物の言葉ではない一般的な励まし(original)。",
        "tier": "free"
      },
      {
        "id": "teresa",
        "name": "マザー・テレサ",
        "nameEn": "Mother Teresa",
        "region": "MK/IN",
        "field": "humanitarian",
        "era": "1910–1997",
        "stance": "compassion",
        "rank": 1,
        "isPremium": true,
        "packId": "pack_human",
        "color": "#6fa8a0",
        "tier": "free"
      },
      {
        "id": "lincoln",
        "name": "エイブラハム・リンカーン",
        "nameEn": "Abraham Lincoln",
        "region": "US",
        "field": "leader",
        "era": "1809–1865",
        "stance": "endurance",
        "rank": 1,
        "isPremium": true,
        "packId": "pack_leader",
        "color": "#7a6f57",
        "tier": "free"
      },
      {
        "id": "ali",
        "name": "モハメド・アリ",
        "nameEn": "Muhammad Ali",
        "region": "US",
        "field": "sports",
        "era": "1942–2016",
        "stance": "confidence",
        "rank": 2,
        "isPremium": true,
        "packId": "pack_sports",
        "color": "#c0603a",
        "tier": "free"
      },
      {
        "id": "scripture_bible",
        "name": "聖書の言葉",
        "nameEn": "The Bible",
        "tradition": "christianity",
        "field": "scripture",
        "stance": "sacred",
        "rank": 9,
        "isPremium": true,
        "packId": "pack_scripture",
        "color": "#caa45d",
        "tier": "free"
      },
      {
        "id": "scripture_quran",
        "name": "クルアーンの言葉",
        "nameEn": "The Quran",
        "tradition": "islam",
        "field": "scripture",
        "stance": "sacred",
        "rank": 9,
        "isPremium": true,
        "packId": "pack_scripture",
        "color": "#caa45d",
        "tier": "free"
      },
      {
        "id": "scripture_dhammapada",
        "name": "法句経（ダンマパダ）の言葉",
        "nameEn": "The Dhammapada",
        "tradition": "buddhism",
        "field": "scripture",
        "stance": "sacred",
        "rank": 9,
        "isPremium": true,
        "packId": "pack_scripture",
        "color": "#caa45d",
        "tier": "free"
      },
      {
        "id": "confucius",
        "name": "孔子",
        "nameEn": "Confucius",
        "region": "CN",
        "field": "thought",
        "era": "BC551–BC479",
        "stance": "virtue",
        "rank": 2,
        "isPremium": false,
        "packId": "pack_free",
        "color": "#8f7355",
        "tier": "free"
      },
      {
        "id": "gandhi",
        "name": "マハトマ・ガンジー",
        "nameEn": "Mahatma Gandhi",
        "region": "IN",
        "field": "thought",
        "era": "1869–1948",
        "stance": "nonviolence",
        "rank": 4,
        "isPremium": false,
        "packId": "pack_free",
        "color": "#b08968",
        "tier": "free"
      },
      {
        "id": "keller",
        "name": "ヘレン・ケラー",
        "nameEn": "Helen Keller",
        "region": "US",
        "field": "humanitarian",
        "era": "1880–1968",
        "stance": "overcoming",
        "rank": 5,
        "isPremium": false,
        "packId": "pack_free",
        "color": "#a0825f",
        "tier": "free"
      },
      {
        "id": "seneca",
        "name": "セネカ",
        "nameEn": "Seneca",
        "region": "Rome",
        "field": "thought",
        "era": "BC1頃–AD65",
        "stance": "stoic",
        "rank": 7,
        "isPremium": false,
        "packId": "pack_free",
        "color": "#6e6a5c",
        "tier": "free"
      },
      {
        "id": "eleanor",
        "name": "エレノア・ルーズベルト",
        "nameEn": "Eleanor Roosevelt",
        "region": "US",
        "field": "leader",
        "era": "1884–1962",
        "stance": "courage",
        "rank": 3,
        "isPremium": false,
        "packId": "pack_free",
        "color": "#8a7a9c",
        "tier": "free"
      },
      {
        "id": "curie",
        "name": "マリ・キュリー",
        "nameEn": "Marie Curie",
        "region": "PL/FR",
        "field": "science",
        "era": "1867–1934",
        "stance": "perseverance",
        "rank": 4,
        "isPremium": true,
        "packId": "pack_science",
        "color": "#5f6caf",
        "tier": "paid"
      },
      {
        "id": "einstein",
        "name": "アルベルト・アインシュタイン",
        "nameEn": "Albert Einstein",
        "region": "DE/US",
        "field": "science",
        "era": "1879–1955",
        "stance": "curiosity",
        "rank": 6,
        "isPremium": true,
        "packId": "pack_science",
        "color": "#4f7d8c",
        "tier": "paid"
      }
    ]
  },
  "events": {
    "version": 1,
    "categories": [
      "work",
      "relationship",
      "love",
      "study",
      "money",
      "health",
      "self"
    ],
    "events": [
      {
        "id": "work_overwhelm_01",
        "category": "work",
        "mood": "down",
        "title": "やることが多すぎて、潰れそう。",
        "body": "仕事が積み上がり、どこから手をつければいいか分からない。心も体も限界に近い。",
        "advices": [
          {
            "sageId": "original",
            "quote": "一度に運ぶ必要はない。次の一歩だけを見よう。",
            "note": "",
            "effects": {
              "mind": 4
            },
            "quoteEn": "You don't have to carry it all at once. Look only at the next step."
          },
          {
            "sageId": "lincoln",
            "quote": "成功しようというあなた自身の決意こそが、何よりも大切だと、常に心に留めておきなさい。",
            "quoteOriginal": "Always bear in mind that your own resolution to succeed is more important than any other.",
            "source": "Letter to Isham Reavis, 1855-11-05",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 5,
              "passion": 7
            }
          },
          {
            "sageId": "curie",
            "quote": "進歩への道は、速くもなければ、楽でもないと、私は教わってきました。",
            "quoteOriginal": "I was taught that the way of progress was neither swift nor easy.",
            "source": "『ピエール・キュリー』(Pierre Curie), 1923",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 6,
              "wisdom": 6
            }
          },
          {
            "sageId": "scripture_quran",
            "tradition": "islam",
            "quote": "本当に困難と共に、安楽はある。本当に困難と共に、安楽はある。",
            "quoteOriginal": "فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ۝ إِنَّ مَعَ الْعُسْرِ يُسْرًا",
            "source": "クルアーン 第94章(アッ・シャルフ) 5–6節",
            "note": "聖典の言葉として引用。",
            "verified": true,
            "rank": 5,
            "effects": {
              "mind": 14,
              "wisdom": 8
            },
            "quoteEn": "Indeed, with hardship comes ease. Indeed, with hardship comes ease."
          }
        ],
        "titleEn": "There's too much to do — I'm about to break.",
        "bodyEn": "Work keeps piling up and I don't know where to start. My mind and body are near their limit.",
        "tier": "free"
      },
      {
        "id": "money_worry_01",
        "category": "money",
        "mood": "down",
        "title": "お金がない。将来が不安でたまらない。",
        "body": "収入も貯金も心もとない。お金のことを考えると、夜も眠れない。",
        "advices": [
          {
            "sageId": "original",
            "quote": "不安は、あなたが真剣に生きている証拠。まず今日の一歩から。",
            "note": "",
            "effects": {
              "mind": 4
            },
            "quoteEn": "Anxiety is proof you're taking life seriously. Start with just today's step."
          },
          {
            "sageId": "confucius",
            "quote": "不義にして富み、且つ貴きは、我に於いて浮雲の如し。",
            "quoteOriginal": "不義而富且貴、於我如浮雲。",
            "source": "論語 述而第七",
            "note": "正しくない富や地位は、自分には浮雲のようなもの、の意。",
            "verified": true,
            "effects": {
              "mind": 5,
              "wisdom": 8
            },
            "quoteEn": "Wealth and honor gained unjustly are to me as drifting clouds."
          },
          {
            "sageId": "einstein",
            "quote": "成功した人間になろうとするより、価値ある人間になろうとしなさい。",
            "quoteOriginal": "Try not to become a man of success, but rather try to become a man of value.",
            "source": "LIFE誌(William Miller), 1955",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 6,
              "wisdom": 7
            }
          }
        ],
        "titleEn": "I have no money. The future terrifies me.",
        "bodyEn": "My income and savings are both shaky. Thinking about money keeps me up at night.",
        "tier": "free"
      },
      {
        "id": "self_doubt_01",
        "category": "self",
        "mood": "down",
        "title": "自分に、まったく自信が持てない。",
        "body": "何をやってもダメな気がする。周りと比べては落ち込んでしまう。",
        "advices": [
          {
            "sageId": "original",
            "quote": "比べる相手は他人ではなく、昨日のあなた。",
            "note": "",
            "effects": {
              "mind": 5
            },
            "quoteEn": "The one to compare with is not others, but yesterday's you."
          },
          {
            "sageId": "curie",
            "quote": "人生は誰にとっても楽ではありません。でも、それがどうしたというのでしょう。私たちは忍耐を、そして何よりも自分自身への自信を持たねばなりません。自分は何かのために才能を授かっている、それは必ず成し遂げられるのだ、と信じることです。",
            "quoteOriginal": "Life is not easy for any of us. But what of that? We must have perseverance and above all confidence in ourselves. We must believe that we are gifted for something, and that this thing must be attained.",
            "source": "エーヴ・キュリー『キュリー夫人伝』(Madame Curie), 1937（V.Sheean 訳, p.222）",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 7,
              "passion": 7,
              "wisdom": 4
            }
          },
          {
            "sageId": "ali",
            "quote": "練習の一分一秒が嫌だった。だが私は自分に言った。『やめるな。今苦しめ。そして残りの人生をチャンピオンとして生きろ』と。",
            "quoteOriginal": "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'",
            "source": "Muhammad Ali Center 公式『In His Own Words』",
            "note": "本人の言葉として公式機関が掲載。",
            "verified": true,
            "effects": {
              "mind": 7,
              "passion": 9
            }
          }
        ],
        "titleEn": "I can't find any confidence in myself.",
        "bodyEn": "I feel I fail at everything. I compare myself to others and sink.",
        "tier": "free"
      },
      {
        "id": "lonely_01",
        "category": "relationship",
        "mood": "down",
        "title": "ひとりぼっちで、心細い。",
        "body": "周りに頼れる人がいない気がする。孤独が胸に重くのしかかる。",
        "advices": [
          {
            "sageId": "original",
            "quote": "あなたが思うより、世界はあなたに優しくできている。",
            "note": "",
            "effects": {
              "mind": 5
            },
            "quoteEn": "The world is kinder to you than you think."
          },
          {
            "sageId": "confucius",
            "quote": "徳は孤ならず、必ず隣あり。",
            "quoteOriginal": "徳不孤、必有鄰。",
            "source": "論語 里仁第四",
            "note": "誠実に生きる人は孤立しない。必ず理解者が現れる。",
            "verified": true,
            "effects": {
              "mind": 7,
              "bonds": 6
            },
            "quoteEn": "Virtue is never solitary; it is sure to have neighbors."
          },
          {
            "sageId": "teresa",
            "quote": "孤独と、必要とされていないという感覚こそ、最も恐ろしい貧しさです。",
            "quoteOriginal": "Loneliness and the feeling of being unwanted is the most terrible poverty.",
            "source": "マザー・テレサ(広く文献に記録)",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 6,
              "bonds": 5
            }
          },
          {
            "sageId": "scripture_bible",
            "tradition": "christianity",
            "quote": "すべて重荷を負うて苦労している者は、わたしのもとに来なさい。あなたがたを休ませてあげよう。",
            "quoteOriginal": "Come to me, all you who are weary and burdened, and I will give you rest.",
            "source": "新約聖書 マタイによる福音書 11:28",
            "note": "聖典の言葉として引用。",
            "verified": true,
            "rank": 5,
            "effects": {
              "mind": 15,
              "wisdom": 8
            }
          }
        ],
        "titleEn": "I feel all alone and uneasy.",
        "bodyEn": "It feels like there's no one to rely on. Loneliness weighs heavy on my chest.",
        "tier": "free"
      },
      {
        "id": "health_illness_01",
        "category": "health",
        "mood": "down",
        "title": "体を壊してしまった。先が不安。",
        "body": "思いがけず体調を崩した。これからどうなるのか、不安が押し寄せる。",
        "advices": [
          {
            "sageId": "original",
            "quote": "休むことは、負けることではない。回復もまた、前進。",
            "note": "",
            "effects": {
              "mind": 5
            },
            "quoteEn": "To rest is not to lose. Recovering, too, is moving forward."
          },
          {
            "sageId": "keller",
            "quote": "世界は苦しみに満ちている。けれど、それを乗り越える力もまた、世界には満ちている。",
            "quoteOriginal": "Although the world is full of suffering, it is also full of the overcoming of it.",
            "source": "ヘレン・ケラー『楽天主義』(Optimism), 1903",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 9,
              "wisdom": 6
            }
          },
          {
            "sageId": "scripture_quran",
            "tradition": "islam",
            "quote": "アッラーは、誰にも、その者が負いきれない重荷を負わせることはない。",
            "quoteOriginal": "لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا",
            "source": "クルアーン 第2章(アル・バカラ) 286節",
            "note": "聖典の言葉として引用。",
            "verified": true,
            "rank": 5,
            "effects": {
              "mind": 14,
              "wisdom": 8
            },
            "quoteEn": "God does not burden any soul beyond what it can bear."
          }
        ],
        "titleEn": "My health has broken down. I'm anxious about what's ahead.",
        "bodyEn": "I fell ill unexpectedly. Worry about what comes next floods over me.",
        "tier": "free"
      },
      {
        "id": "work_boss_01",
        "category": "work",
        "mood": "lost",
        "title": "上司と、どうしても合わない。",
        "body": "顔を合わせるだけで気が重い。仕事に行くのが、つらく感じる。",
        "titleEn": "I just can't get along with my boss.",
        "bodyEn": "Just seeing them weighs on me. Going to work feels hard.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "相手は変えられない。でも、自分の受け取り方は選べる。",
            "note": "",
            "effects": {
              "mind": 5,
              "wisdom": 4
            },
            "quoteEn": "You can't change others, but you can choose how you receive them."
          },
          {
            "sageId": "confucius",
            "quote": "己の欲せざる所、人に施すこと勿れ。",
            "quoteOriginal": "己所不欲、勿施於人。",
            "source": "論語 衛霊公第十五",
            "note": "",
            "verified": true,
            "effects": {
              "wisdom": 7,
              "bonds": 4
            },
            "quoteEn": "Do not impose on others what you do not wish for yourself."
          },
          {
            "sageId": "seneca",
            "quote": "人は現実よりも、想像の中でより多く苦しむ。",
            "quoteOriginal": "We suffer more often in imagination than in reality.",
            "source": "セネカ『倫理書簡集』13",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 6,
              "wisdom": 6
            },
            "quoteEn": "We suffer more often in imagination than in reality."
          }
        ]
      },
      {
        "id": "relationship_quarrel_01",
        "category": "relationship",
        "mood": "down",
        "title": "大切な人と、ぶつかってしまった。",
        "body": "言い過ぎたかもしれない。気まずさが、胸に残っている。",
        "titleEn": "I clashed with someone I care about.",
        "bodyEn": "Maybe I said too much. The awkwardness lingers in my chest.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "謝るのに、遅すぎることはない。小さなひと言から。",
            "note": "",
            "effects": {
              "mind": 5,
              "bonds": 5
            },
            "quoteEn": "It's never too late to apologize. Start with a small word."
          },
          {
            "sageId": "scripture_dhammapada",
            "quote": "この世では、怨みに報いるに怨みをもってしては、ついに怨みの息むことがない。怨みをすててこそ息む。",
            "quoteOriginal": "na hi verena verāni, sammantīdha kudācanaṃ; averena ca sammanti, esa dhammo sanantano.",
            "source": "法句経(ダンマパダ) 第5偈",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 10,
              "wisdom": 8,
              "bonds": 4
            },
            "quoteEn": "Hatred is never appeased by hatred. By non-hatred alone is it appeased."
          },
          {
            "sageId": "teresa",
            "quote": "私たちの誰もが大きなことをできるわけではない。でも、小さなことを大きな愛をもって行うことはできる。",
            "quoteOriginal": "Not all of us can do great things. But we can do small things with great love.",
            "source": "マザー・テレサ",
            "note": "",
            "verified": true,
            "effects": {
              "bonds": 7,
              "mind": 4
            },
            "quoteEn": "Not all of us can do great things. But we can do small things with great love."
          }
        ]
      },
      {
        "id": "love_unrequited_01",
        "category": "love",
        "mood": "down",
        "title": "好きな人に、想いが届かない。",
        "body": "近づきたいのに、勇気が出ない。期待しては、落ち込む。",
        "titleEn": "My feelings aren't reaching the one I love.",
        "bodyEn": "I want to get closer but can't find the courage. I hope, then I sink.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "結果は選べない。でも、心からの一歩は、いつでもあなたの誇りになる。",
            "note": "",
            "effects": {
              "mind": 5,
              "passion": 5
            },
            "quoteEn": "You can't choose the outcome, but a heartfelt step is always yours to be proud of."
          },
          {
            "sageId": "teresa",
            "quote": "痛むほどに愛するなら、もう痛みはなくなり、ただ、より深い愛だけが残る。",
            "quoteOriginal": "I have found the paradox, that if you love until it hurts, there can be no more hurt, only more love.",
            "source": "マザー・テレサ（ノーベル平和賞講演 1979）",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 6,
              "bonds": 5
            },
            "quoteEn": "If you love until it hurts, there can be no more hurt, only more love."
          },
          {
            "sageId": "original",
            "quote": "焦らなくていい。あなたの価値は、誰かの返事で決まるものではない。",
            "note": "",
            "effects": {
              "mind": 5,
              "wisdom": 4
            },
            "quoteEn": "No need to rush. Your worth isn't decided by anyone's reply."
          }
        ]
      },
      {
        "id": "study_motivation_01",
        "category": "study",
        "mood": "lost",
        "title": "勉強に、まったく身が入らない。",
        "body": "やらなきゃと分かっているのに、机に向かえない。",
        "titleEn": "I can't focus on studying at all.",
        "bodyEn": "I know I have to, yet I can't sit at my desk.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "やる気は、始めたあとに付いてくる。まず5分だけ、開いてみよう。",
            "note": "",
            "effects": {
              "mind": 4,
              "passion": 5
            },
            "quoteEn": "Motivation follows action. Just open it for five minutes."
          },
          {
            "sageId": "confucius",
            "quote": "学びて時にこれを習う、亦た説ばしからずや。",
            "quoteOriginal": "學而時習之、不亦説乎。",
            "source": "論語 学而第一",
            "note": "",
            "verified": true,
            "effects": {
              "wisdom": 6,
              "passion": 4
            },
            "quoteEn": "To learn, and at due times practice what you have learned — is that not a pleasure?"
          },
          {
            "sageId": "original",
            "quote": "完璧を目指さなくていい。今日のひと頁が、未来をつくる。",
            "note": "",
            "effects": {
              "wisdom": 5
            },
            "quoteEn": "You don't have to be perfect. Today's one page builds your future."
          }
        ]
      },
      {
        "id": "money_spend_01",
        "category": "money",
        "mood": "lost",
        "title": "つい使いすぎて、お金が貯まらない。",
        "body": "分かっているのに、衝動を抑えられない自分が、嫌になる。",
        "titleEn": "I overspend and can never save.",
        "bodyEn": "I know better, yet I can't control the urge — and I hate that about myself.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "自分を責めなくていい。気づけた今日が、変わりはじめる日。",
            "note": "",
            "effects": {
              "mind": 5
            },
            "quoteEn": "Don't blame yourself. The day you noticed is the day change begins."
          },
          {
            "sageId": "seneca",
            "quote": "貧しいのは、持っているものが少ない人ではなく、もっと欲しがる人である。",
            "quoteOriginal": "non qui parum habet, sed qui plus cupit, pauper est.",
            "source": "セネカ『倫理書簡集』2",
            "note": "",
            "verified": true,
            "effects": {
              "wisdom": 6,
              "wealth": 4,
              "mind": 4
            },
            "quoteEn": "It is not the man who has too little, but the man who craves more, that is poor."
          },
          {
            "sageId": "original",
            "quote": "小さな『使わない』を、ひとつだけ選んでみよう。",
            "note": "",
            "effects": {
              "wealth": 6,
              "wisdom": 3
            },
            "quoteEn": "Choose just one small \"I won't spend\" today."
          }
        ]
      },
      {
        "id": "health_unwell_01",
        "category": "health",
        "mood": "down",
        "title": "体の調子が悪くて、心まで沈む。",
        "body": "思うように動けない。このまま良くならないのでは、と不安になる。",
        "titleEn": "My body is unwell, and my heart sinks with it.",
        "bodyEn": "I can't move as I want. I fear it may never get better.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "今日は休むのも、立派な前進。回復は、あなたのペースで。",
            "note": "",
            "effects": {
              "mind": 7
            },
            "quoteEn": "Resting today is real progress too. Heal at your own pace."
          },
          {
            "sageId": "scripture_bible",
            "quote": "すべて重荷を負うて苦労している者は、わたしのもとに来なさい。休ませてあげよう。",
            "quoteOriginal": "Come to me, all you who are weary and burdened, and I will give you rest.",
            "source": "新約聖書 マタイによる福音書 11章28節",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 12,
              "wisdom": 6
            },
            "quoteEn": "Come to me, all you who are weary and burdened, and I will give you rest."
          },
          {
            "sageId": "keller",
            "quote": "世界は苦しみに満ちている。しかし、それを乗り越える力にも満ちている。",
            "quoteOriginal": "Although the world is full of suffering, it is also full of the overcoming of it.",
            "source": "ヘレン・ケラー『楽天主義』1903",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 6,
              "wisdom": 5
            },
            "quoteEn": "Although the world is full of suffering, it is also full of the overcoming of it."
          }
        ]
      },
      {
        "id": "self_confidence_01",
        "category": "self",
        "mood": "down",
        "title": "自分に、自信が持てない。",
        "body": "何をしても、自分はダメだと感じてしまう。",
        "titleEn": "I can't believe in myself.",
        "bodyEn": "Whatever I do, I feel like I'm not good enough.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "自信は『できた経験』から育つ。今日の小さな一つを、数えよう。",
            "note": "",
            "effects": {
              "mind": 4,
              "passion": 5
            },
            "quoteEn": "Confidence grows from small wins. Count one of yours today."
          },
          {
            "sageId": "keller",
            "quote": "楽観は、成就へと導く信念である。希望と自信なくしては、何事も成し得ない。",
            "quoteOriginal": "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.",
            "source": "ヘレン・ケラー『楽天主義』1903",
            "note": "",
            "verified": true,
            "effects": {
              "passion": 6,
              "mind": 4
            },
            "quoteEn": "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence."
          },
          {
            "sageId": "original",
            "quote": "あなたが思うより、あなたはずっと多くを乗り越えてきた。",
            "note": "",
            "effects": {
              "mind": 5
            },
            "quoteEn": "You've overcome far more than you give yourself credit for."
          }
        ]
      },
      {
        "id": "self_compare_01",
        "category": "self",
        "mood": "lost",
        "title": "つい、他人と比べて落ち込む。",
        "body": "SNSを見ては、自分だけ取り残された気持ちになる。",
        "titleEn": "I compare myself to others and feel low.",
        "bodyEn": "Scrolling social media, I feel like only I am left behind.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "比べる相手は、昨日の自分だけでいい。",
            "note": "",
            "effects": {
              "mind": 5,
              "wisdom": 4
            },
            "quoteEn": "The only one worth comparing to is yesterday's you."
          },
          {
            "sageId": "confucius",
            "quote": "人の己を知らざるを患えず、人を知らざるを患う。",
            "quoteOriginal": "不患人之不己知、患不知人也。",
            "source": "論語 学而第一",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 5,
              "wisdom": 6
            },
            "quoteEn": "Do not be troubled that others do not know you; be troubled that you do not know others."
          },
          {
            "sageId": "original",
            "quote": "あなたの花は、あなたの季節に咲く。",
            "note": "",
            "effects": {
              "mind": 5
            },
            "quoteEn": "Your flower blooms in your own season."
          }
        ]
      },
      {
        "id": "work_career_01",
        "category": "work",
        "mood": "lost",
        "title": "今の仕事のままで、いいのだろうか。",
        "body": "毎日が同じことの繰り返し。この先が、見えない。",
        "titleEn": "Is it okay to stay in this job?",
        "bodyEn": "Every day is the same. I can't see what lies ahead.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "迷いは、次へ進みたい心のサイン。焦らず、棚卸しから。",
            "note": "",
            "effects": {
              "mind": 4,
              "wisdom": 5
            },
            "quoteEn": "Doubt is your heart wanting to move forward. Start by taking stock."
          },
          {
            "sageId": "eleanor",
            "quote": "恐れと正面から向き合うたびに、人は強さと勇気と自信を得る。",
            "quoteOriginal": "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.",
            "source": "エレノア・ルーズベルト『You Learn by Living』1960",
            "note": "",
            "verified": true,
            "effects": {
              "passion": 7,
              "mind": 4
            },
            "quoteEn": "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face."
          },
          {
            "sageId": "original",
            "quote": "正解の道はない。あなたが歩けば、そこが道になる。",
            "note": "",
            "effects": {
              "passion": 5,
              "wisdom": 4
            },
            "quoteEn": "There is no \"right\" road. Where you walk becomes the road."
          }
        ]
      },
      {
        "id": "lonely_02",
        "category": "relationship",
        "mood": "down",
        "title": "ひとりぼっちだと、感じてしまう。",
        "body": "周りに人はいても、心は満たされない。",
        "titleEn": "I feel all alone.",
        "bodyEn": "Even with people around, my heart feels empty.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "孤独は、あなたが深く生きている証。その感受性は、宝。",
            "note": "",
            "effects": {
              "mind": 5,
              "wisdom": 4
            },
            "quoteEn": "Loneliness is proof you live deeply. That sensitivity is a treasure."
          },
          {
            "sageId": "original",
            "quote": "「さびしい」と言える日が、きっと来る。その日まで、この灯火がそばにいる。",
            "note": "",
            "effects": {
              "mind": 6,
              "bonds": 3
            },
            "quoteEn": "A day will come when you can say \"I'm lonely.\" Until then, this beacon stays beside you."
          },
          {
            "sageId": "scripture_quran",
            "quote": "われを念え。そうすれば、われもあなたがたを念う。",
            "quoteOriginal": "فَاذْكُرُونِي أَذْكُرْكُمْ",
            "source": "クルアーン 第2章(アル・バカラ) 152節",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 10,
              "wisdom": 8
            },
            "quoteEn": "Remember Me; I will remember you."
          }
        ]
      },
      {
        "id": "self_newchallenge_01",
        "category": "self",
        "mood": "high",
        "title": "新しいことに、挑戦してみたい！",
        "body": "やってみたい気持ちが湧いている。でも、少しだけ怖い。",
        "titleEn": "I want to try something new!",
        "bodyEn": "The urge to try is rising. But I'm a little scared, too.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "その高鳴りを、信じよう。最初の一歩は、今この瞬間に踏める。",
            "note": "",
            "effects": {
              "passion": 8,
              "mind": 4
            },
            "quoteEn": "Trust that thrill. The first step can be taken right now."
          },
          {
            "sageId": "keller",
            "quote": "人生は、勇敢な冒険か、さもなくば無か。",
            "quoteOriginal": "Life is either a daring adventure or nothing at all.",
            "source": "ヘレン・ケラー『The Open Door』1957",
            "note": "",
            "verified": true,
            "effects": {
              "passion": 8,
              "wisdom": 4
            },
            "quoteEn": "Life is either a daring adventure or nothing at all."
          },
          {
            "sageId": "original",
            "quote": "失敗は、挑んだ者だけがもらえる勲章。",
            "note": "",
            "effects": {
              "passion": 6,
              "wisdom": 4
            },
            "quoteEn": "Failure is a medal given only to those who dared."
          }
        ]
      },
      {
        "id": "self_grateful_01",
        "category": "self",
        "mood": "high",
        "title": "今ある幸せを、大切にしたい。",
        "body": "当たり前の毎日が、ふと、愛おしく感じられた。",
        "titleEn": "I want to cherish the happiness I have now.",
        "bodyEn": "My ordinary days suddenly felt precious.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "気づけたことが、すでに豊かさ。その心を、明日へ。",
            "note": "",
            "effects": {
              "mind": 5,
              "bonds": 4
            },
            "quoteEn": "Noticing is already richness. Carry that heart into tomorrow."
          },
          {
            "sageId": "scripture_bible",
            "quote": "すべてのことについて、感謝しなさい。",
            "quoteOriginal": "Give thanks in all circumstances.",
            "source": "新約聖書 テサロニケの信徒への手紙一 5章18節",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 8,
              "wisdom": 6
            },
            "quoteEn": "Give thanks in all circumstances."
          },
          {
            "sageId": "original",
            "quote": "幸せは、探すものではなく、気づくもの。",
            "note": "",
            "effects": {
              "mind": 5
            },
            "quoteEn": "Happiness is not something to find, but something to notice."
          }
        ]
      },
      {
        "id": "work_recognition_01",
        "category": "work",
        "mood": "high",
        "title": "頑張りが、認められた。",
        "body": "努力を見てもらえた気がして、心が温かい。",
        "titleEn": "My effort was recognized.",
        "bodyEn": "It felt like someone saw my hard work, and my heart is warm.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "その喜びを、ちゃんと味わおう。努力が実った、確かな証。",
            "note": "",
            "effects": {
              "passion": 6,
              "mind": 5
            },
            "quoteEn": "Savor this joy fully. It's solid proof your effort bore fruit."
          },
          {
            "sageId": "keller",
            "quote": "最善を尽くせば、自分の人生に、そして誰かの人生に、どんな奇跡が起こるか分からない。",
            "quoteOriginal": "When we do the best we can, we never know what miracle is wrought in our life, or in the life of another.",
            "source": "ヘレン・ケラー",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 5,
              "wisdom": 5
            },
            "quoteEn": "When we do the best we can, we never know what miracle is wrought in our life, or in the life of another."
          },
          {
            "sageId": "original",
            "quote": "次の一歩も、あなたなら歩める。今日の自分を、誇っていい。",
            "note": "",
            "effects": {
              "passion": 6
            },
            "quoteEn": "You can take the next step too. Be proud of who you were today."
          }
        ]
      },
      {
        "id": "relationship_distance_01",
        "category": "relationship",
        "mood": "lost",
        "title": "人との距離感が、わからない。",
        "body": "近づきすぎても、離れすぎても不安。ちょうどいいが、つかめない。",
        "titleEn": "I can't gauge the right distance with people.",
        "bodyEn": "Too close or too far both make me anxious. I can't find the balance.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "近すぎず、遠すぎず。心地よい距離は、少しずつ見つかっていく。",
            "note": "",
            "effects": {
              "mind": 5,
              "bonds": 4
            },
            "quoteEn": "Not too close, not too far. A comfortable distance is found little by little."
          },
          {
            "sageId": "confucius",
            "quote": "君子は和して同ぜず。",
            "quoteOriginal": "君子和而不同。",
            "source": "論語 子路第十三",
            "note": "",
            "verified": true,
            "effects": {
              "wisdom": 6,
              "bonds": 4
            },
            "quoteEn": "The wise are in harmony with others, yet do not merely conform."
          },
          {
            "sageId": "original",
            "quote": "合わせすぎなくていい。あなたのままで、つながれる人がいる。",
            "note": "",
            "effects": {
              "bonds": 5,
              "mind": 4
            },
            "quoteEn": "You don't have to over-adapt. There are people you connect with as you are."
          }
        ]
      },
      {
        "id": "love_beginning_01",
        "category": "love",
        "mood": "high",
        "title": "恋が、始まりそう。",
        "body": "誰かを想うと、胸がどきどきする。こんな気持ち、久しぶり。",
        "titleEn": "A new love may be beginning.",
        "bodyEn": "Thinking of someone makes my heart race. It's been a while.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "そのときめきを、大切に。心が動くというのは、素敵なこと。",
            "note": "",
            "effects": {
              "passion": 7,
              "mind": 4
            },
            "quoteEn": "Cherish that flutter. To have your heart move is a beautiful thing."
          },
          {
            "sageId": "scripture_bible",
            "quote": "愛は忍耐強い。愛は情け深い。",
            "quoteOriginal": "Love is patient, love is kind.",
            "source": "新約聖書 コリントの信徒への手紙一 13章4節",
            "note": "",
            "verified": true,
            "effects": {
              "mind": 8,
              "bonds": 5
            },
            "quoteEn": "Love is patient, love is kind."
          },
          {
            "sageId": "original",
            "quote": "結果を急がず、この時間そのものを楽しもう。",
            "note": "",
            "effects": {
              "passion": 5,
              "mind": 4
            },
            "quoteEn": "Don't rush the outcome — enjoy this time itself."
          }
        ]
      },
      {
        "id": "study_goal_01",
        "category": "study",
        "mood": "high",
        "title": "目標に向かって、頑張りたい。",
        "body": "やりたいことが、見えてきた。この勢いを、続けたい。",
        "titleEn": "I want to work toward my goal.",
        "bodyEn": "I'm starting to see what I want. I want to keep this momentum.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "その意気を、燃やし続けよう。コツコツが、いちばん遠くまで行く。",
            "note": "",
            "effects": {
              "passion": 7,
              "wisdom": 4
            },
            "quoteEn": "Keep that fire burning. Steady steps carry you the farthest."
          },
          {
            "sageId": "eleanor",
            "quote": "できないと思うことを、やってみなさい。",
            "quoteOriginal": "You must do the things you think you cannot do.",
            "source": "エレノア・ルーズベルト『You Learn by Living』1960",
            "note": "",
            "verified": true,
            "effects": {
              "passion": 7,
              "mind": 4
            },
            "quoteEn": "You must do the things you think you cannot do."
          },
          {
            "sageId": "original",
            "quote": "大きな目標も、今日のひと頁から。あなたは、もう歩き出している。",
            "note": "",
            "effects": {
              "wisdom": 5
            },
            "quoteEn": "Even big goals start with today's page. You've already begun."
          }
        ]
      },
      {
        "id": "health_habit_01",
        "category": "health",
        "mood": "lost",
        "title": "生活習慣を変えたいのに、続かない。",
        "body": "決めたことが三日でくずれる。意志が弱い自分が、情けない。",
        "titleEn": "I want to change my habits but can't keep it up.",
        "bodyEn": "What I decide falls apart in three days. I feel pathetic for my weak will.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "三日坊主でも、また始めればいい。続けるとは、何度でも戻ること。",
            "note": "",
            "effects": {
              "mind": 6
            },
            "quoteEn": "Even if you slip after three days, just begin again. To continue is to return, again and again."
          },
          {
            "sageId": "gandhi",
            "quote": "強さは身体の力からではなく、不屈の意志から生まれる。",
            "quoteOriginal": "Strength does not come from physical capacity. It comes from an indomitable will.",
            "source": "ガンジー『Young India』",
            "note": "",
            "verified": true,
            "effects": {
              "passion": 6,
              "mind": 4
            },
            "quoteEn": "Strength does not come from physical capacity. It comes from an indomitable will."
          },
          {
            "sageId": "original",
            "quote": "大きく変えなくていい。今日できる、小さな一つから。",
            "note": "",
            "effects": {
              "mind": 5,
              "wisdom": 3
            },
            "quoteEn": "You don't have to change big. Start with one small thing today."
          }
        ]
      },
      {
        "id": "self_purpose_01",
        "category": "self",
        "mood": "lost",
        "title": "自分が、何をしたいのか、わからない。",
        "body": "周りは進んでいるのに、自分だけ目標がない気がする。",
        "titleEn": "I don't know what I want to do.",
        "bodyEn": "Everyone's moving ahead, and I feel like only I have no goal.",
        "tier": "free",
        "advices": [
          {
            "sageId": "original",
            "quote": "『わからない』は、出発点。答えは、歩きながら見つかっていく。",
            "note": "",
            "effects": {
              "mind": 5,
              "wisdom": 5
            },
            "quoteEn": "\"I don't know\" is a starting point. The answer is found as you walk."
          },
          {
            "sageId": "seneca",
            "quote": "どの港を目指すか分からなければ、どんな風も、追い風にはならない。",
            "quoteOriginal": "If one does not know to which port one is sailing, no wind is favorable.",
            "source": "セネカ『倫理書簡集』71",
            "note": "",
            "verified": true,
            "effects": {
              "wisdom": 7,
              "mind": 4
            },
            "quoteEn": "If one does not know to which port one is sailing, no wind is favorable."
          },
          {
            "sageId": "original",
            "quote": "焦らず、心が少し動く方へ。それが、あなたの羅針盤。",
            "note": "",
            "effects": {
              "wisdom": 5
            },
            "quoteEn": "Don't rush — move toward what stirs your heart even a little. That's your compass."
          }
        ]
      }
    ]
  },
  "legends": {
    "version": 1,
    "legends": []
  }
};
